import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
// import * as casual from 'casual';
import casual from 'casual-browserify';

@Injectable({ providedIn: 'root' })
export class ProductService {

  products = [
    {
      id: 1,
      name: 'Samsung TV',
      type: 'TVs',
      price: 599,
      rating: 4.5,
      description: 'A high-quality Samsung TV.',
      image: 'assets/images/tv.jpg',
    },
    {
      id: 2,
      name: 'iPhone 13',
      type: 'Phones',
      price: 299,
      rating: 4.7,
      description: 'Latest iPhone model.',
      image: 'assets/images/phone.jpg',
    },
    {
      id: 3,
      name: 'Steam Games',
      type: 'Video Games',
      price: 499,
      rating: 4.8,
      description: 'PS5 - Next-gen PlayStation console.',
      image: 'assets/images/video-games.jpg',
    },
    {
      id: 4,
      name: 'Dryer',
      type: 'Appliances',
      price: 799,
      rating: 4.8,
      description: 'Appliance.',
      image: 'assets/images/appliances.jpg',
    },
    {
      id: 5,
      name: 'PS5',
      type: 'Video Games',
      price: 499,
      rating: 4.8,
      description: 'Next-gen PlayStation console.',
      image: 'assets/images/video-games.jpg',
    },
    {
      id: 6,
      name: 'Samsung TV',
      type: 'TVs',
      price: 599,
      rating: 4.5,
      description: 'A high-quality Samsung TV.',
      image: 'assets/images/tv.jpg',
    },
    {
      id: 7,
      name: 'iPhone 11',
      type: 'Phones',
      price: 99,
      rating: 4.7,
      description: 'Latest iPhone model.',
      image: 'assets/images/phone.jpg',
    },
    {
      id: 8,
      name: 'Xbox lite',
      type: 'Video Games',
      price: 499,
      rating: 4.8,
      description: 'PS5 - Next-gen PlayStation console.',
      image: 'assets/images/video-games.jpg',
    },
    {
      id: 9,
      name: 'Air Conditionar',
      type: 'Appliances',
      price: 1299,
      rating: 4.8,
      description: 'Appliance.',
      image: 'assets/images/appliances.jpg',
    },
    {
      id: 10,
      name: 'PS5 digital',
      type: 'Video Games',
      price: 399,
      rating: 4.8,
      description: 'Next-gen PlayStation console.',
      image: 'assets/images/video-games.jpg',
    },
    {
      id: 11,
      name: 'Samsung TV',
      type: 'TVs',
      price: 599,
      rating: 4.5,
      description: 'A high-quality Samsung TV.',
      image: 'assets/images/tv.jpg',
    },
    {
      id: 12,
      name: 'iPhone 16',
      type: 'Phones',
      price: 1399,
      rating: 4.7,
      description: 'Latest iPhone model.',
      image: 'assets/images/phone.jpg',
    },
    {
      id: 13,
      name: 'Nintendo',
      type: 'Video Games',
      price: 499,
      rating: 4.8,
      description: 'PS5 - Next-gen PlayStation console.',
      image: 'assets/images/video-games.jpg',
    },
    {
      id: 14,
      name: 'Refrigerator',
      type: 'Appliances',
      price: 1199,
      rating: 4.8,
      description: 'Appliance.',
      image: 'assets/images/appliances.jpg',
    },
    {
      id: 15,
      name: 'PS5 Pro',
      type: 'Video Games',
      price: 799,
      rating: 4.8,
      description: 'Next-gen PlayStation console.',
      image: 'assets/images/video-games.jpg',
    },
    {
      id: 16,
      name: 'Samsung TV',
      type: 'TVs',
      price: 599,
      rating: 4.5,
      description: 'A high-quality Samsung TV.',
      image: 'assets/images/tv.jpg',
    },
    {
      id: 17,
      name: 'iPhone 14',
      type: 'Phones',
      price: 599,
      rating: 4.7,
      description: 'Latest iPhone model.',
      image: 'assets/images/phone.jpg',
    },
    {
      id: 18,
      name: 'Video Games',
      type: 'Video Games',
      price: 499,
      rating: 4.8,
      description: 'PS5 - Next-gen PlayStation console.',
      image: 'assets/images/video-games.jpg',
    },
    {
      id: 19,
      name: 'Washing Machine',
      type: 'Appliances',
      price: 1999,
      rating: 4.8,
      description: 'Appliance.',
      image: 'assets/images/appliances.jpg',
    },
    {
      id: 20,
      name: 'Xbox',
      type: 'Video Games',
      price: 699,
      rating: 4.8,
      description: 'Next-gen PlayStation console.',
      image: 'assets/images/video-games.jpg',
    },
  ];

  getProducts(): Observable<any[]> {
    return of(this.products);
  }

 
}
